routes/web.php
<?php

use App\Http\Controllers\DoctorController;
use App\Http\Controllers\FrontOfficeController;
use App\Http\Controllers\HospitalController;
use App\Http\Controllers\MealController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\ResponseController;
use App\Http\Controllers\SurveyController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [FrontOfficeController::class, 'index'])->name('frontoffice.index');
Route::get('/front-games', [FrontOfficeController::class, 'games'])->name('frontoffice.games');
Route::get('/front-meals', [FrontOfficeController::class, 'meals'])->name('frontoffice.meals');
Route::get('surveys/{survey}/create', [FrontOfficeController::class, 'create'])->name('frontoffice.create');
Route::post('surveys/submissions/store', [FrontOfficeController::class, 'store'])->name('frontoffice.store');

Route::group([
    'domain' => config('boilerplate.app.domain', ''),
    'middleware' => ['web', 'boilerplate.locale'],
    'as' => 'boilerplate.',
], function () {

    //all routes must be protected by auth
    Route::group(['middleware' => ['auth', 'boilerplate.emailverified']], function () {

        // Admin routes
        Route::group(['middleware' => ['role:admin']], function () {
            Route::get('hospitals', [HospitalController::class, 'index'])->name('hospitals.index');
            Route::post('hospitals', [HospitalController::class, 'store'])->name('hospitals.store');
            Route::get('hospitals/create', [HospitalController::class, 'create'])->name('hospitals.create');
            Route::get('hospitals/{hospital}/edit', [HospitalController::class, 'edit'])->name('hospitals.edit');
            Route::put('hospitals/{hospital}/update', [HospitalController::class, 'update'])->name('hospitals.update');
        });

        // Manager routes
        Route::group(['middleware' => ['role:manager']], function () {
            Route::get('doctors', [DoctorController::class, 'index'])->name('doctors.index');
            Route::post('doctors', [DoctorController::class, 'store'])->name('doctors.store');
            Route::get('doctors/create', [DoctorController::class, 'create'])->name('doctors.create');
            Route::get('doctors/{doctor}/edit', [DoctorController::class, 'edit'])->name('doctors.edit');
            Route::put('doctors/{doctor}/update', [DoctorController::class, 'update'])->name('doctors.update');
        });
        // managers doctors routes
        Route::group(['middleware' => ['role:manager|doctor']], function () {
            Route::get('surveys', [SurveyController::class, 'index'])->name('surveys.index');
            Route::post('surveys', [SurveyController::class, 'store'])->name('surveys.store');
            Route::get('surveys/{survey}/show', [SurveyController::class, 'show'])->name('surveys.show');
            Route::get('surveys/{survey}/edit', [SurveyController::class, 'edit'])->name('surveys.edit');
            Route::put('surveys/{survey}/update', [SurveyController::class, 'update'])->name('surveys.update');
            Route::delete('surveys/{survey}/destroy', [SurveyController::class, 'destroy'])->name('surveys.destroy');

            Route::get('responses', [ResponseController::class, 'index'])->name('responses.index');
            Route::get('responses/{survey}/edit', [ResponseController::class, 'edit'])->name('responses.edit');
            Route::delete('responses/{survey}/destroy', [ResponseController::class, 'destroy'])->name('responses.destroy');

            Route::post('surveys/{survey}/questions/store', [QuestionController::class, 'store'])->name('questions.store');
            Route::get('surveys/questions/{question}/edit', [QuestionController::class, 'edit'])->name('questions.edit');
            Route::put('surveys/questions/{question}/update', [QuestionController::class, 'update'])->name('questions.update');
            Route::delete('surveys/questions/{question}/destroy', [QuestionController::class, 'destroy'])->name('questions.destroy');

            Route::get('meals', [MealController::class, 'index'])->name('meals.index');
            Route::post('meals', [MealController::class, 'store'])->name('meals.store');
            Route::get('meals/create', [MealController::class, 'create'])->name('meals.create');
            Route::get('meals/{meal}/edit', [MealController::class, 'edit'])->name('meals.edit');
            Route::put('meals/{meal}/update', [MealController::class, 'update'])->name('meals.update');
            Route::delete('meals/{meal}/destroy', [MealController::class, 'destroy'])->name('meals.destroy');
        });
    });
});

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use HasFactory;
    const CheckBox = 'Checkbox';
    const DragAndDrop = 'Drag and drop';
    protected $guarded = [];

    public function survey()
    {
        return $this->belongsTo(Survey::class);
    }

    public function options()
    {
        return $this->hasMany(Option::class);
    }
}

app/Models/Survey.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Survey extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function questions()
    {
        return $this->hasMany(Question::class);
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Option;
use App\Models\Question;
use App\Models\Survey;
use App\Rules\CorrectOptionsRule;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

class QuestionController extends Controller
{
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View
     */
    public function edit($id)
    {
        $currentUser = Auth::user();
        if ($currentUser->hasRole('manager')) {
            $question = Question::where('id', $id)->whereHas('survey', function ($q) use ($currentUser) {
                $q->where('manager_id', $currentUser->id);
            })->first();
        } elseif ($currentUser->hasRole('doctor')) {
            $question = Question::where('id', $id)->whereHas('survey', function ($q) use ($currentUser) {
                $q->where('manager_id', $currentUser->manager_id);
            })->first();
        }
        if ($question) {
            return view('surveys.questions.edit', [
                'question' => $question,
            ]);
        }
        abort(403);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return RedirectResponse
     */
    public function update($id, Request $request)
    {
        $currentUser = Auth::user();
        if ($currentUser->hasRole('manager')) {
            $question = Question::where('id', $id)->whereHas('survey', function ($q) use ($currentUser) {
                $q->where('manager_id', $currentUser->id);
            })->first();
        } elseif ($currentUser->hasRole('doctor')) {
            $question = Question::where('id', $id)->whereHas('survey', function ($q) use ($currentUser) {
                $q->where('manager_id', $currentUser->manager_id);
            })->first();
        }
        $this->validate($request, [
            'name' => 'required|unique:questions,name,' . $id,
            'options' => ['required', 'array', 'min:2', new CorrectOptionsRule],
            'options.*.correct' => 'required|in:on,off',
            'options.*.option_name' => 'required|string',
            'options.*.file' => 'required_without:options.*.old_file|nullable|image|mimes:jpeg,png,gif',
            'options.*.old' => [
                'nullable',
                function ($attribute, $value, $fail) use ($request, $id) {
                    $options = collect($request->input('options'));

                    // Check for duplicate 'old' values within the 'options' array
                    $duplicates = $options->pluck('old')->duplicates()->all();
                    $duplicates = array_filter($duplicates, function ($value) {
                        return $value !== null;
                    });

                    if (!empty($duplicates)) {
                        $fail('Duplicate values are not allowed in the options.');
                    }

                    // Check if the selected option exists for this question
                    if (!empty($value)) {
                        $optionExists = Option::where('id', $value)
                            ->where('question_id', $id)
                            ->exists();

                        if (!$optionExists) {
                            $fail('The selected option does not exist for this question.');
                        }
                    }
                },
            ],
        ], [
            'options.required' => 'At least two options are required.',
            'options.array' => 'The options must be an array.',
            'options.min' => 'At least two options are required.',
            'options.*.correct.required' => 'The correct flag is required for each option.',
            'options.*.correct.in' => 'The correct flag must be either "on" or "off" for each option.',
            'options.*.option_name.required' => 'The option name is required for each option.',
            'options.*.option_name.string' => 'The option name must be a string for each option.',
            'options.*.file.required_without' => 'The file is required for each option.',
            'options.*.file.image' => 'The file must be an image for each option.',
            'options.*.file.mimes' => 'The file must be a JPEG, PNG, or GIF image for each option.',
        ]);

        if ($question) {
            $oldOptions = collect($request->options)->pluck('old')->all();
            $oldOptions = array_filter($oldOptions, function ($value) {
                return $value !== null;
            });
            if (empty(array_filter($oldOptions))) {
                // If all elements are null, delete all options for the specified question_id
                $deletedOptions = Option::where('question_id', $question->id)->get();
            } else {
                $deletedOptions = Option::where('question_id', $question->id)
                    ->whereNotIn('id', $oldOptions)->get();
            }

            foreach ($deletedOptions as $option) {
                if (File::exists($option->image)) {
                    // Delete old image if it exists
                    File::delete($option->image);
                }
                $option->delete();
            }
            $question->name = $request->name;
            $question->save();

            foreach ($request->options as $op) {
                if (isset($op['old'])) {
                    // edit old option
                    $option = Option::find($op['old']);
                    $option->text = $op['option_name'];
                    $option->correct_answer = $op['correct'];
                    if (isset($op['file'])) {
                        // change image of old option
                        $oldImagePath = $option->image; // Store the old image path
                        if (File::exists($oldImagePath)) {
                            // Delete old image if it exists
                            File::delete($oldImagePath);
                        }
                        $file = $op['file'];
                        $option->image = $file->storeAs('public/surveys/' . $question->survey->id . '_survey/' . $question->id . '_question', $option->id . '_option_' . $file->getClientOriginalName());
                        $option->image = str_replace('public/', 'storage/app/public/', $option->image);
                    }
                    $option->save();
                } else {
                    //new option
                    $option = new Option();
                    $option->question_id = $question->id;
                    $option->text = $op['option_name'];
                    $option->correct_answer = $op['correct'];
                    $option->save();
                    $file = $op['file'];
                    $option->image = $file->storeAs('public/surveys/' . $question->survey->id . '_survey/' . $question->id . '_question', $option->id . '_option_' . $file->getClientOriginalName());
                    $option->image = str_replace('public/', 'storage/app/public/', $option->image);
                    $option->save();
                }
            }

            return redirect()->route('boilerplate.questions.edit', $question)
                ->with('growl', [__('boilerplate::surveys.successmod'), 'success']);
        }
        abort(403);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return RedirectResponse
     */

    public function store($id, Request $request)
    {
        $currentUser = Auth::user();
        if ($currentUser->hasRole('manager')) {
            $survey = Survey::where('id', $id)->where('manager_id', $currentUser->id)->first();
        } elseif ($currentUser->hasRole('doctor')) {
            $survey = Survey::where('id', $id)->where('manager_id', $currentUser->manager_id)->first();
        }
        if ($survey) {
            $this->validate($request, [
                'name' => 'required|unique:questions,name',
                'options' => ['required', 'array', 'min:2', new CorrectOptionsRule],
                'options.*.file' => 'required|image|mimes:jpeg,png,gif',
                'options.*.correct' => 'required|in:on,off',
                'options.*.option_name' => 'required|string',
            ], [
                'options.required' => 'At least two options are required.',
                'options.array' => 'The options must be an array.',
                'options.min' => 'At least two options are required.',
                'options.*.file.required' => 'The file is required for each option.',
                'options.*.file.image' => 'The file must be an image for each option.',
                'options.*.file.mimes' => 'The file must be a JPEG, PNG, or GIF image for each option.',
                'options.*.correct.required' => 'The correct flag is required for each option.',
                'options.*.correct.in' => 'The correct flag must be either "on" or "off" for each option.',
                'options.*.option_name.required' => 'The option name is required for each option.',
                'options.*.option_name.string' => 'The option name must be a string for each option.',
            ]);
            $question = new Question();
            $question->survey_id = $id;
            $question->name = $request->name;
            $question->order = count($survey->questions) + 1;
            $question->type = Question::CheckBox;
            $question->save();

            foreach ($request->options as $op) {
                $option = new Option();
                $option->question_id = $question->id;
                $option->text = $op['option_name'];
                $option->correct_answer = $op['correct'];
                $option->save();
                $file = $op['file'];

resources/views/surveys/questions/edit.blade.php
@extends('boilerplate::layout.index', [
'title' => __('boilerplate::surveys.title'),
'subtitle' => $question->survey->name . ': ' . $question->name,
'breadcrumb' => [
__('boilerplate::surveys.title') => 'boilerplate.surveys.index',
$question->survey->name,
$question->name,
]
])


@section('content')
<form method="POST" action="{{ route('boilerplate.questions.update',$question->id) }}" autocomplete="off" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="row">
        <div class="col-12 pb-3">
            <a href="{{ route('boilerplate.surveys.edit',$question->survey->id) }}" class="btn btn-default" data-toggle="tooltip" title="{{$question->survey->name}}">
                <span class="far fa-arrow-alt-circle-left text-muted"></span>
            </a>
            <span class="btn-group float-right">
                <button type="submit" class="btn btn-primary">
                    @lang('boilerplate::surveys.save')
                </button>
            </span>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            @component('boilerplate::card', ['title' => 'boilerplate::surveys.edit_question'])
            @if($errors->any())
            <div class="alert alert-danger">
                @php
                $displayedErrors = [];
                @endphp
                @foreach ($errors->all() as $error)
                @if (!in_array($error, $displayedErrors) && strpos($error, 'name') !== 0)
                <div>{{ $error }}</div>
                @php
                $displayedErrors[] = $error;
                @endphp
                @endif
                @endforeach
            </div>
            @endif
            @component('boilerplate::input', ['name' => 'name', 'label' => 'boilerplate::surveys.edit.name', 'value'=>$question->name])@endcomponent
            <p><button type="button" class="btn btn-info mt-3" id="add-option-btn">@lang('boilerplate::surveys.add_option')</button></p>
            <div class="tab-content">
                <div class="tab-pane fade show active" id="options" role="tabpanel" aria-labelledby="options-tab">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="options-table">
                            <thead>
                                <tr>
                                    <th>@lang('boilerplate::surveys.upload_files')</th>
                                    <th>@lang('boilerplate::surveys.correct_option')</th>
                                    <th>@lang('boilerplate::surveys.option_name')</th>
                                    <th>@lang('boilerplate::surveys.action')</th>
                                </tr>
                            </thead>
                            <tbody id="options-body">
                                <!-- First row -->
                                @foreach($question->options as $key => $option)
                                <tr class="option-row">
                                    <td>
                                        <label for="file_{{ $key }}" id="label_file_{{ $key }}" style="display: none;">@lang('boilerplate::surveys.upload_file')</label>
                                        <input type="file" id="file_{{ $key }}" name="options[{{ $key }}][file]" style="display: none;">

                                        <div id="image-container_{{ $key }}" class="image-container">
                                            <img id="image-preview_{{ $key }}" src="{{ asset($option->image) }}" alt="Option Image" width="100">
                                            <button type="button" class="btn btn-danger remove-image" data-key="{{ $key }}">X</button>
                                            <input class="form-check-input" type="hidden" value="{{$option->id}}" name="options[{{ $key }}][old_file]">
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-check">
                                            <input class="form-check-input" type="hidden" value="{{$option->id}}" name="options[{{ $key }}][old]">
                                            <input class="form-check-input" type="hidden" value="{{$option->correct_answer}}" name="options[{{ $key }}][correct]">
                                            <input class="form-check-input" type="checkbox" id="correct_{{ $key }}" name="options[{{ $key }}][correct]" {{ $option->correct_answer === 'on' ? 'checked' : '' }}>
                                            <label class="form-check-label" for="correct_{{ $key }}">@lang('boilerplate::surveys.correct_option')</label>
                                        </div>
                                    </td>
                                    <td>
                                        <input type="text" id="option_name_{{ $key }}" name="options[{{ $key }}][option_name]" class="form-control" value="{{$option->text}}">
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-danger delete-option">Delete</button>
                                    </td>
                                </tr>


                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            @endcomponent
        </div>
    </div>
</form>
<script>
    window.onload = function() {
        // Counter for unique IDs
        let optionCounter = <?php echo json_encode(count($question->options)) ?>;

        // Function to add a new option row to the table
        function addOptionRow() {
            optionCounter++;

            let optionRow = `<tr class="option-row">
        <td>
            <label for="file_${optionCounter}">@lang('boilerplate::surveys.upload_file')</label>
            <input type="file" id="file_${optionCounter}" name="options[${optionCounter}][file]">
        </td>
        <td>
            <div class="form-check">
                <input class="form-check-input" type="hidden" value="off" name="options[${optionCounter}][correct]">
                <input class="form-check-input" type="checkbox" id="correct_${optionCounter}" name="options[${optionCounter}][correct]">
                <label class="form-check-label" for="correct_${optionCounter}">@lang('boilerplate::surveys.correct_option')</label>
            </div>
        </td>
        <td>
            <input type="text" id="option_name_${optionCounter}" name="options[${optionCounter}][option_name]" class="form-control">
        </td>
        <td>
            <button type="button" class="btn btn-danger delete-option">Delete</button>
        </td>
        </tr>
        `;

            $('#options-body').append(optionRow);
        }

        // Add option button click event
        $('#add-option-btn').click(function() {
            addOptionRow();
        });

        // Delete option button click event (delegated to handle dynamically added delete buttons)
        $('#options-body').on('click', '.delete-option', function() {
            $(this).closest('.option-row').remove();
        });

        // Add event listener for checkbox change
        document.addEventListener('change', function(event) {
            const checkbox = event.target;
            if (checkbox.type === 'checkbox') {
                checkbox.previousElementSibling.value = checkbox.checked ? 'on' : 'off';
            }
        });

        $('.remove-image').on('click', function() {
            var key = $(this).data('key');
            $('#image-container_' + key).remove(); // Remove the parent div
            $('#label_file_' + key).show(); // Show the label file input
            $('#file_' + key).show(); // Show the file input
            $('#file_' + key).val(''); // Clear the file input value
        });
    };
</script>
@endsection