routes/web.php
<?php

use App\Http\Controllers\DoctorController;
use App\Http\Controllers\FrontOfficeController;
use App\Http\Controllers\HospitalController;
use App\Http\Controllers\MealController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\ResponseController;
use App\Http\Controllers\SurveyController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [FrontOfficeController::class, 'index'])->name('frontoffice.index');
Route::get('/front-games', [FrontOfficeController::class, 'games'])->name('frontoffice.games');
Route::get('/front-meals', [FrontOfficeController::class, 'meals'])->name('frontoffice.meals');
Route::get('surveys/{survey}/create', [FrontOfficeController::class, 'create'])->name('frontoffice.create');
Route::post('surveys/submissions/store', [FrontOfficeController::class, 'store'])->name('frontoffice.store');

Route::group([
    'domain' => config('boilerplate.app.domain', ''),
    'middleware' => ['web', 'boilerplate.locale'],
    'as' => 'boilerplate.',
], function () {

    //all routes must be protected by auth
    Route::group(['middleware' => ['auth', 'boilerplate.emailverified']], function () {

        // Admin routes
        Route::group(['middleware' => ['role:admin']], function () {
            Route::get('hospitals', [HospitalController::class, 'index'])->name('hospitals.index');
            Route::post('hospitals', [HospitalController::class, 'store'])->name('hospitals.store');
            Route::get('hospitals/create', [HospitalController::class, 'create'])->name('hospitals.create');
            Route::get('hospitals/{hospital}/edit', [HospitalController::class, 'edit'])->name('hospitals.edit');
            Route::put('hospitals/{hospital}/update', [HospitalController::class, 'update'])->name('hospitals.update');
        });

        // Manager routes
        Route::group(['middleware' => ['role:manager']], function () {
            Route::get('doctors', [DoctorController::class, 'index'])->name('doctors.index');
            Route::post('doctors', [DoctorController::class, 'store'])->name('doctors.store');
            Route::get('doctors/create', [DoctorController::class, 'create'])->name('doctors.create');
            Route::get('doctors/{doctor}/edit', [DoctorController::class, 'edit'])->name('doctors.edit');
            Route::put('doctors/{doctor}/update', [DoctorController::class, 'update'])->name('doctors.update');
        });
        // managers doctors routes
        Route::group(['middleware' => ['role:manager|doctor']], function () {
            Route::get('surveys', [SurveyController::class, 'index'])->name('surveys.index');
            Route::post('surveys', [SurveyController::class, 'store'])->name('surveys.store');
            Route::get('surveys/{survey}/show', [SurveyController::class, 'show'])->name('surveys.show');
            Route::get('surveys/{survey}/edit', [SurveyController::class, 'edit'])->name('surveys.edit');
            Route::put('surveys/{survey}/update', [SurveyController::class, 'update'])->name('surveys.update');
            Route::delete('surveys/{survey}/destroy', [SurveyController::class, 'destroy'])->name('surveys.destroy');

            Route::get('responses', [ResponseController::class, 'index'])->name('responses.index');
            Route::get('responses/{survey}/edit', [ResponseController::class, 'edit'])->name('responses.edit');
            Route::delete('responses/{survey}/destroy', [ResponseController::class, 'destroy'])->name('responses.destroy');

            Route::post('surveys/{survey}/questions/store', [QuestionController::class, 'store'])->name('questions.store');
            Route::get('surveys/questions/{question}/edit', [QuestionController::class, 'edit'])->name('questions.edit');
            Route::put('surveys/questions/{question}/update', [QuestionController::class, 'update'])->name('questions.update');
            Route::delete('surveys/questions/{question}/destroy', [QuestionController::class, 'destroy'])->name('questions.destroy');

            Route::get('meals', [MealController::class, 'index'])->name('meals.index');
            Route::post('meals', [MealController::class, 'store'])->name('meals.store');
            Route::get('meals/create', [MealController::class, 'create'])->name('meals.create');
            Route::get('meals/{meal}/edit', [MealController::class, 'edit'])->name('meals.edit');
            Route::put('meals/{meal}/update', [MealController::class, 'update'])->name('meals.update');
            Route::delete('meals/{meal}/destroy', [MealController::class, 'destroy'])->name('meals.destroy');
        });
    });
});

app/Models/Boilerplate/User.php
<?php

namespace App\Models\Boilerplate;

use Carbon\Carbon;
use Creativeorange\Gravatar\Facades\Gravatar;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laratrust\Traits\LaratrustUserTrait;
use App\Events\Boilerplate\UserCreated;
use App\Events\Boilerplate\UserDeleted;
use App\Events\Boilerplate\UserSaved;
use App\Models\Hospital;
use App\Notifications\Boilerplate\NewUser;
use App\Notifications\Boilerplate\ResetPassword;
use App\Notifications\Boilerplate\VerifyEmail;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;
    use LaratrustUserTrait;
    use SoftDeletes;

    protected $casts = ['settings' => 'array'];

    protected $fillable = [
        'active',
        'last_name',
        'first_name',
        'email',
        'hospital_id',
        'manager_id',
        'doctor_id',
        'password',
        'remember_token',
        'last_login',
        'settings',
    ];

    protected $hidden = ['password', 'remember_token'];

    protected $dispatchesEvents = [
        'created' => UserCreated::class,
        'deleted' => UserDeleted::class,
        'saved'   => UserSaved::class,
    ];

    /**
     * Send the email verification notification.
     *
     * @return void
     */
    public function sendEmailVerificationNotification()
    {
        if (config('boilerplate.auth.verify_email')) {
            $this->notify(new VerifyEmail());
        }
    }

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPassword($token));
    }

    /**
     * Send notification when a new user is created.
     *
     * @param  string  $token
     */
    public function sendNewUserNotification($token)
    {
        $this->notify(new NewUser($token, $this));
    }

    /**
     * Return last name in uppercase by default.
     *
     * @param  $value
     * @return string
     */
    public function getLastNameAttribute($value)
    {
        return mb_strtoupper($value);
    }

    /**
     * Return first name with first char of every word in uppercase.
     *
     * @param  $value
     * @return string
     */
    public function getFirstNameAttribute($value)
    {
        return mb_convert_case($value, MB_CASE_TITLE);
    }

    /**
     * Return a concatenation of first name and last_name if field name does not exists.
     *
     * @return string
     */
    public function getNameAttribute()
    {
        return $this->getAttribute('first_name') . ' ' . $this->getAttribute('last_name');
    }

    /**
     * Return last login date formatted.
     *
     * @param  string  $format
     * @param  string  $default
     * @return mixed|string
     */
    public function getLastLogin($format = 'YYYY-MM-DD HH:mm:ss', $default = '')
    {
        if ($this->last_login === null) {
            return $default;
        }

        return Carbon::createFromTimeString($this->last_login)->isoFormat($format);
    }

    /**
     * Return role list as a string.
     *
     * @return string
     */
    public function getRolesList()
    {
        $res = [];
        foreach ($this->roles as $role) {
            $res[] = __($role->display_name);
        }

        return empty($res) ? '-' : implode(', ', $res);
    }

    /**
     * Return true if user has an avatar image.
     *
     * @return bool
     */
    public function hasAvatar()
    {
        return is_file($this->getAvatarPathAttribute());
    }

    /**
     * Check if current user has an avatar.
     *
     * @return string|false
     */
    public function getAvatarPathAttribute()
    {
        return public_path('images/avatars/' . md5($this->id . $this->email) . '.jpg');
    }

    /**
     * Delete avatar image.
     *
     * @return bool
     */
    public function deleteAvatar()
    {
        if ($this->hasAvatar()) {
            return unlink($this->getAvatarPathAttribute());
        }

        return false;
    }

    /**
     * Return current user avatar uri.
     *
     * @return string
     */
    public function getAvatarUrlAttribute()
    {
        if (is_file($this->avatar_path)) {
            return asset('images/avatars/' . md5($this->id . $this->email) . '.jpg?t=' . filemtime($this->avatar_path));
        }

        return 'https://ui-avatars.com/api/?' . http_build_query([
            'background' => 'F0F0F0',
            'color' => '333',
            'size' => 170,
            'name' => $this->getNameAttribute(),
        ]);
    }

    /**
     * Get avatar image from Gravatar.com.
     *
     * @return bool
     */
    public function getAvatarFromGravatar()
    {
        if (!Gravatar::exists($this->getAttribute('email'))) {
            return false;
        }

        if ($this->hasAvatar()) {
            unlink($this->getAvatarPathAttribute());
        }

        $src = Gravatar::get($this->getAttribute('email'), ['size' => 250]);
        $img = file_get_contents($src);
        $destDir = public_path('images/avatars/');

        if (!is_dir($destDir)) {
            mkdir($destDir, 0766, true);
            file_put_contents($destDir . '/.gitignore', "*\r\n!.gitignore");
        }

        file_put_contents($this->getAvatarPathAttribute(), $img);

        return true;
    }

    /**
     * Retrieve or store a setting with a given name or fall back to the default.
     *
     * @param  string|array  $name
     * @param  mixed  $default
     * @return mixed|null
     */
    public function setting($name, $default = null)
    {
        if (is_array($name)) {
            $this->settings = array_merge($this->settings ?? [], $name);

            return $this->save();
        }

        $setting = $this->settings[$name] ?? $default;

        if ($setting === 'true') {
            return true;
        }

        if ($setting === 'false') {
            return false;
        }

        return $setting;
    }

    /**
     * Get the manager, doctor and child record associated with the hospital
     */
    public function hospital()
    {
        return $this->belongsTo(Hospital::class);
    }
}

app/Http/Controllers/DoctorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Boilerplate\User;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DoctorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        return view('doctors.list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('doctors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return RedirectResponse
     */

    public function store(Request $request)
    {
        $this->validate($request, [
            'last_name'  => 'required',
            'first_name' => 'required',
            'email'      => 'required|email|unique:users,email,NULL,id,deleted_at,NULL',
        ]);

        $userModel = config('boilerplate.auth.providers.users.model');
        $user = $userModel::withTrashed()->updateOrCreate(['email' => $request->email], [
            'active' => $request->active,
            'hospital_id' => Auth::user()->hospital_id,
            'manager_id' => Auth::user()->id,
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'password' => bcrypt(Str::random(8)),
            'remember_token' => Str::random(32),
            'deleted_at' => null,
        ]);
        $user->restore();
        $user->roles()->sync([3]);

        $user->sendNewUserNotification($user->remember_token);

        return redirect()->route('boilerplate.doctors.edit', $user)
            ->with('growl', [__('boilerplate::users.successadd'), 'success']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        if ($user->hasRole('doctor')) {
            if ($user->manager_id == Auth::user()->id) {
                return view('doctors.edit', [
                    'user' => $user,
                ]);
            }
            abort(403);
        }
        abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return RedirectResponse
     */
    public function update($id, Request $request)
    {
        $userModel = config('boilerplate.auth.providers.users.model');
        $user = $userModel::findOrFail($id);
        if ($user->hasRole(['doctor'])) {
            if ($user->manager_id == Auth::user()->id) {
                $this->validate($request, [
                    'last_name'  => 'required',
                    'first_name' => 'required',
                    'email'      => 'required|email|unique:users,email,' . $id,
                ]);

                $user->update([
                    'last_name'  => $request->last_name,
                    'first_name' =>  $request->first_name,
                    'email'      => $request->email,
                    'active' => $request->active,

                ]);


                return redirect()->route('boilerplate.doctors.edit', $user)
                    ->with('growl', [__('boilerplate::users.successmod'), 'success']);
            }
            abort(403);
        }
        abort(404);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
    }
}

resources/views/doctors/create.blade.php
@extends('boilerplate::layout.index', [
'title' => __('boilerplate::users.title'),
'subtitle' => __('boilerplate::users.create_doctor.title'),
'breadcrumb' => [
__('boilerplate::users.title') => 'boilerplate.doctors.index',
__('boilerplate::users.create_doctor.title')
]
])

@section('content')
<form method="POST" action="{{ route('boilerplate.doctors.store') }}" autocomplete="off">
    @csrf
    <div class="row">
        <div class="col-12 pb-3">
            <a href="{{ route("boilerplate.doctors.index") }}" class="btn btn-default" data-toggle="tooltip" title="@lang('boilerplate::doctors.returntolist')">
                <span class="far fa-arrow-alt-circle-left text-muted"></span>
            </a>
            <span class="btn-group float-right">
                <button type="submit" class="btn btn-primary">
                    @lang('boilerplate::users.save')
                </button>
            </span>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            @component('boilerplate::card', ['title' => 'boilerplate::users.informations'])
            @component('boilerplate::select2', ['name' => 'active', 'label' => 'boilerplate::users.status', 'minimum-results-for-search' => '-1'])
            <option value="1" @if (old('active', 1)=='1' ) selected="selected" @endif>@lang('boilerplate::users.active')</option>
            <option value="0" @if (old('active')=='0' ) selected="selected" @endif>@lang('boilerplate::users.inactive')</option>
            @endcomponent
            <div class="row">
                <div class="col-md-6 col-lg-12 col-xl-6">
                    @component('boilerplate::input', ['name' => 'first_name', 'label' => 'boilerplate::users.firstname', 'autofocus' => true])@endcomponent
                </div>
                <div class="col-md-6 col-lg-12 col-xl-6">
                    @component('boilerplate::input', ['name' => 'last_name', 'label' => 'boilerplate::users.lastname'])@endcomponent
                </div>
            </div>
            @component('boilerplate::input', ['name' => 'email', 'label' => 'boilerplate::users.email', 'help' => 'boilerplate::users.create.help'])@endcomponent
            @endcomponent
        </div>
    </div>
</form>
@endsection

resources/views/doctors/edit.blade.php
@extends('boilerplate::layout.index', [
'title' => __('boilerplate::users.title'),
'subtitle' => __('boilerplate::users.edit_doctor.title'),
'breadcrumb' => [
__('boilerplate::users.title') => 'boilerplate.doctors.index',
__('boilerplate::users.edit_doctor.title')
]
])

@section('content')
<form action="{{ route('boilerplate.doctors.update', $user->id) }}" method="POST" autocomplete="off">
    @csrf
    @method('PUT')
    <div class="row">
    <div class="col-12 pb-3">
        <a href="{{ route("boilerplate.doctors.index") }}" class="btn btn-default" data-toggle="tooltip" title="@lang('boilerplate::users.returntolist')">
            <span class="far fa-arrow-alt-circle-left text-muted"></span>
        </a>
        <span class="btn-group float-right">
            <button type="submit" class="btn btn-primary">
                @lang('boilerplate::users.save')
            </button>
        </span>
    </div>
    <div class="col-md-6">
        @component('boilerplate::card', ['color' => 'orange'])
        <div class="d-flex flex-column flex-md-row">
            <div id="avatar-wrapper">
                <img src="{{ $user->avatar_url }}" class="avatar-img" alt="avatar" />
            </div>
            <div class="mt-3 mt-md-0 pl-md-3">
                <span class="info-box-text">
                    <p class="mb-0"><strong class="h3">{{ $user->name  }}</strong></p>
                    <p class="">{{ $user->getRolesList()}} | {{$user->hospital->name}}</p>
                </span>
                <span class="info-box-more">
                    <p>
                        <a href="mailto:{{ $user->email }}" class="btn btn-default">
                            <span class="far fa-fw fa-envelope"></span> {{ $user->email }}
                        </a>
                    </p>
                    <p class="mb-0 text-muted">
                        {{ __('boilerplate::users.profile.subscribedsince', [
                                        'date' => $user->created_at->isoFormat(__('boilerplate::date.lFdY')),
                                        'since' => $user->created_at->diffForHumans()]) }}
                    </p>
                </span>
            </div>
        </div>
        @endcomponent
    </div>

    <div class="col-md-6">

        @component('boilerplate::card', ['title' => __('boilerplate::users.informations')])
        <div class="row">
            @if(Auth::user()->id !== $user->id)
            <div class="col-md-6">
                @component('boilerplate::select2', ['name' => 'active', 'label' => 'boilerplate::users.status', 'minimum-results-for-search' => '-1'])
                <option value="1" @if (old('active', $user->active) == '1') selected="selected" @endif>@lang('boilerplate::users.active')</option>
                <option value="0" @if (old('active', $user->active) == '0') selected="selected" @endif>@lang('boilerplate::users.inactive')</option>
                @endcomponent
            </div>
            @endif
            <div class="col-md-6">
                @component('boilerplate::input', ['name' => 'email', 'label' => 'boilerplate::users.email', 'value' => $user->email])@endcomponent
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                @component('boilerplate::input', ['name' => 'first_name', 'label' => 'boilerplate::users.firstname', 'value' => $user->first_name])@endcomponent
            </div>
            <div class="col-md-6">
                @component('boilerplate::input', ['name' => 'last_name', 'label' => 'boilerplate::users.lastname', 'value' => $user->last_name])@endcomponent
            </div>
        </div>
        @endcomponent
    </div>

</div>
</form>
@endsection

resources/views/doctors/list.blade.php
@extends('boilerplate::layout.index', [
'title' => __('boilerplate::users.title'),
'subtitle' => __('boilerplate::users.list.title'),
'breadcrumb' => [
__('boilerplate::users.list.title') => 'boilerplate.doctors.index'
]
])

@section('content')
<div class="row">
    <div class="col-12 mbl">
        <span class="float-right pb-3">
            <a href="{{ route("boilerplate.doctors.create") }}" class="btn btn-primary">
                @lang('boilerplate::users.create_doctor.title')
            </a>
        </span>
    </div>
</div>

@component('boilerplate::card')

@component('boilerplate::datatable', ['name' => 'doctors']) @endcomponent

@endcomponent
@endsection

@push('css')
<style>
    .img-circle {
        border: 1px solid #CCC
    }
</style>
@endpush