routes/web.php
<?php

use App\Http\Controllers\DoctorController;
use App\Http\Controllers\FrontOfficeController;
use App\Http\Controllers\HospitalController;
use App\Http\Controllers\MealController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\ResponseController;
use App\Http\Controllers\SurveyController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [FrontOfficeController::class, 'index'])->name('frontoffice.index');
Route::get('/front-games', [FrontOfficeController::class, 'games'])->name('frontoffice.games');
Route::get('/front-meals', [FrontOfficeController::class, 'meals'])->name('frontoffice.meals');
Route::get('surveys/{survey}/create', [FrontOfficeController::class, 'create'])->name('frontoffice.create');
Route::post('surveys/submissions/store', [FrontOfficeController::class, 'store'])->name('frontoffice.store');

Route::group([
    'domain' => config('boilerplate.app.domain', ''),
    'middleware' => ['web', 'boilerplate.locale'],
    'as' => 'boilerplate.',
], function () {

    //all routes must be protected by auth
    Route::group(['middleware' => ['auth', 'boilerplate.emailverified']], function () {

        // Admin routes
        Route::group(['middleware' => ['role:admin']], function () {
            Route::get('hospitals', [HospitalController::class, 'index'])->name('hospitals.index');
            Route::post('hospitals', [HospitalController::class, 'store'])->name('hospitals.store');
            Route::get('hospitals/create', [HospitalController::class, 'create'])->name('hospitals.create');
            Route::get('hospitals/{hospital}/edit', [HospitalController::class, 'edit'])->name('hospitals.edit');
            Route::put('hospitals/{hospital}/update', [HospitalController::class, 'update'])->name('hospitals.update');
        });

        // Manager routes
        Route::group(['middleware' => ['role:manager']], function () {
            Route::get('doctors', [DoctorController::class, 'index'])->name('doctors.index');
            Route::post('doctors', [DoctorController::class, 'store'])->name('doctors.store');
            Route::get('doctors/create', [DoctorController::class, 'create'])->name('doctors.create');
            Route::get('doctors/{doctor}/edit', [DoctorController::class, 'edit'])->name('doctors.edit');
            Route::put('doctors/{doctor}/update', [DoctorController::class, 'update'])->name('doctors.update');
        });
        // managers doctors routes
        Route::group(['middleware' => ['role:manager|doctor']], function () {
            Route::get('surveys', [SurveyController::class, 'index'])->name('surveys.index');
            Route::post('surveys', [SurveyController::class, 'store'])->name('surveys.store');
            Route::get('surveys/{survey}/show', [SurveyController::class, 'show'])->name('surveys.show');
            Route::get('surveys/{survey}/edit', [SurveyController::class, 'edit'])->name('surveys.edit');
            Route::put('surveys/{survey}/update', [SurveyController::class, 'update'])->name('surveys.update');
            Route::delete('surveys/{survey}/destroy', [SurveyController::class, 'destroy'])->name('surveys.destroy');

            Route::get('responses', [ResponseController::class, 'index'])->name('responses.index');
            Route::get('responses/{survey}/edit', [ResponseController::class, 'edit'])->name('responses.edit');
            Route::delete('responses/{survey}/destroy', [ResponseController::class, 'destroy'])->name('responses.destroy');

            Route::post('surveys/{survey}/questions/store', [QuestionController::class, 'store'])->name('questions.store');
            Route::get('surveys/questions/{question}/edit', [QuestionController::class, 'edit'])->name('questions.edit');
            Route::put('surveys/questions/{question}/update', [QuestionController::class, 'update'])->name('questions.update');
            Route::delete('surveys/questions/{question}/destroy', [QuestionController::class, 'destroy'])->name('questions.destroy');

            Route::get('meals', [MealController::class, 'index'])->name('meals.index');
            Route::post('meals', [MealController::class, 'store'])->name('meals.store');
            Route::get('meals/create', [MealController::class, 'create'])->name('meals.create');
            Route::get('meals/{meal}/edit', [MealController::class, 'edit'])->name('meals.edit');
            Route::put('meals/{meal}/update', [MealController::class, 'update'])->name('meals.update');
            Route::delete('meals/{meal}/destroy', [MealController::class, 'destroy'])->name('meals.destroy');
        });
    });
});

app/Models/Hospital.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Hospital extends Model
{
    use HasFactory;
    protected $guarded = [];    
}

app/Http/Controllers/HospitalController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\HospitalRequest;
use App\Models\Hospital;
use Illuminate\Http\Request;

class HospitalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        return view('hospitals.list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('hospitals.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return RedirectResponse
     */

    public function store(HospitalRequest $request)
    {
        $hospital = Hospital::create([
            "name" => $request->name,
        ]);

        return redirect()->route('boilerplate.hospitals.edit', $hospital)
            ->with('growl', [__('hospitals.successadd'), 'success']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View
     */
    public function edit(Hospital $hospital)
    {
        return view('hospitals.edit', [
            'hospital' => $hospital,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return RedirectResponse
     */
    public function update(HospitalRequest $request, Hospital $hospital)
    {
        $hospital->update([
            'name' => $request->name,
        ]);

        return redirect()->route('boilerplate.hospitals.edit', $hospital)
            ->with('growl', [__('boilerplate::hospitals.successmod'), 'success']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
    }
}

resources/views/hospitals/create.blade.php
@extends('boilerplate::layout.index', [
'title' => __('boilerplate::hospitals.title'),
'subtitle' => __('boilerplate::hospitals.create.title'),
'breadcrumb' => [
__('boilerplate::hospitals.title') => 'boilerplate.hospitals.index',
__('boilerplate::hospitals.create.title')
]
])

@section('content')
<form method="POST" action="{{ route('boilerplate.hospitals.store') }}" autocomplete="off">
    @csrf
    <div class="row">
        <div class="col-12 pb-3">
            <a href="{{ route("boilerplate.hospitals.index") }}" class="btn btn-default" data-toggle="tooltip" title="@lang('boilerplate::hospitals.returntolist')">
                <span class="far fa-arrow-alt-circle-left text-muted"></span>
            </a>
            <span class="btn-group float-right">
                <button type="submit" class="btn btn-primary">
                    @lang('boilerplate::hospitals.save')
                </button>
            </span>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            @component('boilerplate::card', ['title' => 'boilerplate::hospitals.informations'])
            @component('boilerplate::input', ['name' => 'name', 'label' => 'boilerplate::hospitals.name'])@endcomponent
            @endcomponent
        </div>
    </div>
</form>
@endsection

resources/views/hospitals/edit.blade.php
@extends('boilerplate::layout.index', [
'title' => __('boilerplate::hospitals.title'),
'subtitle' => __('boilerplate::hospitals.edit.title'),
'breadcrumb' => [
__('boilerplate::hospitals.title') => 'boilerplate.hospitals.index',
__('boilerplate::hospitals.edit.title')
]
])

@section('content')
<form action="{{ route('boilerplate.hospitals.update', $hospital->id) }}" method="POST" autocomplete="off">
    @csrf
    @method('PUT')
    <div class="row">
        <div class="col-12 pb-3">
            <a href="{{ route("boilerplate.hospitals.index") }}" class="btn btn-default" data-toggle="tooltip" title="@lang('boilerplate::hospitals.returntolist')">
                <span class="far fa-arrow-alt-circle-left text-muted"></span>
            </a>
            <span class="btn-group float-right">
                <button type="submit" class="btn btn-primary">
                    @lang('boilerplate::hospitals.save')
                </button>
            </span>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            @component('boilerplate::card', ['title' => 'boilerplate::hospitals.informations'])
            @component('boilerplate::input', ['name' => 'name', 'label' => 'boilerplate::hospitals.name','value'=> $hospital->name])@endcomponent
            @endcomponent
        </div>

    </div>
</form>
@endsection

resources/views/hospitals/list.blade.php
@extends('boilerplate::layout.index', [
'title' => __('boilerplate::hospitals.title'),
'subtitle' => __('boilerplate::hospitals.list.title'),
'breadcrumb' => [
__('boilerplate::hospitals.list.title') => 'boilerplate.hospitals.index'
]
])

@section('content')
<div class="row">
    <div class="col-12 mbl">
        <span class="float-right pb-3">
            <a href="{{ route("boilerplate.hospitals.create") }}" class="btn btn-primary">
                @lang('boilerplate::hospitals.create.title')
            </a>
        </span>
    </div>
</div>

@component('boilerplate::card')

@component('boilerplate::datatable', ['name' => 'hospitals']) @endcomponent

@endcomponent
@endsection

@push('css')
<style>
    .img-circle {
        border: 1px solid #CCC
    }
</style>
@endpush