routes/web.php
<?php

use App\Http\Controllers\DoctorController;
use App\Http\Controllers\FrontOfficeController;
use App\Http\Controllers\HospitalController;
use App\Http\Controllers\MealController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\ResponseController;
use App\Http\Controllers\SurveyController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [FrontOfficeController::class, 'index'])->name('frontoffice.index');
Route::get('/front-games', [FrontOfficeController::class, 'games'])->name('frontoffice.games');
Route::get('/front-meals', [FrontOfficeController::class, 'meals'])->name('frontoffice.meals');
Route::get('surveys/{survey}/create', [FrontOfficeController::class, 'create'])->name('frontoffice.create');
Route::post('surveys/submissions/store', [FrontOfficeController::class, 'store'])->name('frontoffice.store');

Route::group([
    'domain' => config('boilerplate.app.domain', ''),
    'middleware' => ['web', 'boilerplate.locale'],
    'as' => 'boilerplate.',
], function () {

    //all routes must be protected by auth
    Route::group(['middleware' => ['auth', 'boilerplate.emailverified']], function () {

        // Admin routes
        Route::group(['middleware' => ['role:admin']], function () {
            Route::get('hospitals', [HospitalController::class, 'index'])->name('hospitals.index');
            Route::post('hospitals', [HospitalController::class, 'store'])->name('hospitals.store');
            Route::get('hospitals/create', [HospitalController::class, 'create'])->name('hospitals.create');
            Route::get('hospitals/{hospital}/edit', [HospitalController::class, 'edit'])->name('hospitals.edit');
            Route::put('hospitals/{hospital}/update', [HospitalController::class, 'update'])->name('hospitals.update');
        });

        // Manager routes
        Route::group(['middleware' => ['role:manager']], function () {
            Route::get('doctors', [DoctorController::class, 'index'])->name('doctors.index');
            Route::post('doctors', [DoctorController::class, 'store'])->name('doctors.store');
            Route::get('doctors/create', [DoctorController::class, 'create'])->name('doctors.create');
            Route::get('doctors/{doctor}/edit', [DoctorController::class, 'edit'])->name('doctors.edit');
            Route::put('doctors/{doctor}/update', [DoctorController::class, 'update'])->name('doctors.update');
        });
        // managers doctors routes
        Route::group(['middleware' => ['role:manager|doctor']], function () {
            Route::get('surveys', [SurveyController::class, 'index'])->name('surveys.index');
            Route::post('surveys', [SurveyController::class, 'store'])->name('surveys.store');
            Route::get('surveys/{survey}/show', [SurveyController::class, 'show'])->name('surveys.show');
            Route::get('surveys/{survey}/edit', [SurveyController::class, 'edit'])->name('surveys.edit');
            Route::put('surveys/{survey}/update', [SurveyController::class, 'update'])->name('surveys.update');
            Route::delete('surveys/{survey}/destroy', [SurveyController::class, 'destroy'])->name('surveys.destroy');

            Route::get('responses', [ResponseController::class, 'index'])->name('responses.index');
            Route::get('responses/{survey}/edit', [ResponseController::class, 'edit'])->name('responses.edit');
            Route::delete('responses/{survey}/destroy', [ResponseController::class, 'destroy'])->name('responses.destroy');

            Route::post('surveys/{survey}/questions/store', [QuestionController::class, 'store'])->name('questions.store');
            Route::get('surveys/questions/{question}/edit', [QuestionController::class, 'edit'])->name('questions.edit');
            Route::put('surveys/questions/{question}/update', [QuestionController::class, 'update'])->name('questions.update');
            Route::delete('surveys/questions/{question}/destroy', [QuestionController::class, 'destroy'])->name('questions.destroy');

            Route::get('meals', [MealController::class, 'index'])->name('meals.index');
            Route::post('meals', [MealController::class, 'store'])->name('meals.store');
            Route::get('meals/create', [MealController::class, 'create'])->name('meals.create');
            Route::get('meals/{meal}/edit', [MealController::class, 'edit'])->name('meals.edit');
            Route::put('meals/{meal}/update', [MealController::class, 'update'])->name('meals.update');
            Route::delete('meals/{meal}/destroy', [MealController::class, 'destroy'])->name('meals.destroy');
        });
    });
});

app/Models/Survey.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Survey extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function questions()
    {
        return $this->hasMany(Question::class);
    }
}

app/Http/Controllers/SurveyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Survey;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Validator;

class SurveyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        return view('surveys.list');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View
     */
    public function edit($id)
    {
        $currentUser = Auth::user();
        if ($currentUser->hasRole('manager')) {
            $survey = Survey::where('id', $id)->where('manager_id', $currentUser->id)->first();
        } elseif ($currentUser->hasRole('doctor')) {
            $survey = Survey::where('id', $id)->where('manager_id', $currentUser->manager_id)->first();
        }
        if ($survey) {
            session(['surveyId' => $survey->id]);
            return view('surveys.edit', [
                'survey' => $survey,
            ]);
        }
        abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return RedirectResponse
     */

    public function store(Request $request)
    {
        $this->validate($request, [
            'name'  => 'required|unique:surveys,name',
            'status'      => 'required|in:0,1',
        ]);
        $currentUser = Auth::user();
        Survey::create([
            'name'  => $request->name,
            'manager_id'  => $currentUser->hasRole('manager') ? $currentUser->id : $currentUser->manager_id,
            'status' =>  $request->status,
        ]);

        return redirect()->route('boilerplate.surveys.index')
            ->with('growl', [__('boilerplate::surveys.successadd'), 'success']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $currentUser = Auth::user();
        if ($currentUser->hasRole('manager')) {
            $survey = Survey::where('id', $id)->where('manager_id', $currentUser->id)->first();
        } elseif ($currentUser->hasRole('doctor')) {
            $survey = Survey::where('id', $id)->where('manager_id', $currentUser->manager_id)->first();
        }
        if ($survey) {
            return  $survey;
        }
        abort(404);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return RedirectResponse
     */
    public function update($id, Request $request)
    {
        $currentUser = Auth::user();
        if ($currentUser->hasRole('manager')) {
            $survey = Survey::where('id', $id)->where('manager_id', $currentUser->id)->first();
        } elseif ($currentUser->hasRole('doctor')) {
            $survey = Survey::where('id', $id)->where('manager_id', $currentUser->manager_id)->first();
        }
        if ($survey) {
            $rules =  [
                'survey_name' => 'required|unique:surveys,name,' . $id,
                'survey_status'      => 'required|in:0,1',
            ];
            $validator = Validator::make($request->all(), $rules);
            if ($validator->fails()) {
                $surveyNameError = $validator->errors()->first('survey_name');
                $surveyStatusError = $validator->errors()->first('survey_status');
                return redirect()->route('boilerplate.surveys.index')
                    ->with('growl', [$surveyNameError . ' ' . $surveyStatusError, 'error']);
            }
            $survey->name = $request->survey_name;
            $survey->status = $request->survey_status;
            $survey->save();

            return redirect()->route('boilerplate.surveys.index')
                ->with('growl', [__('boilerplate::surveys.successmod'), 'success']);
        }
        abort(403);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $currentUser = Auth::user();
        if ($currentUser->hasRole('manager')) {
            $survey = Survey::where('id', $id)->where('manager_id', $currentUser->id)->first();
        } elseif ($currentUser->hasRole('doctor')) {
            $survey = Survey::where('id', $id)->where('manager_id', $currentUser->manager_id)->first();
        }
        if ($survey) {
            // Get the directory path you want to delete
            $directoryPath = storage_path('app/public/surveys/' . $survey->id . '_survey');

            // Check if the directory exists before attempting to delete it
            if (File::exists($directoryPath)) {
                // Delete the directory and its contents
                File::deleteDirectory($directoryPath);
            }
            return response()->json(['success' => $survey->delete() ?? false]);
        }
        abort(403);
    }
}

resources/views/surveys/edit.blade.php
@extends('boilerplate::layout.index', [
'title' => __('boilerplate::surveys.title'),
'subtitle' => $survey->name,
'breadcrumb' => [
__('boilerplate::surveys.title') => 'boilerplate.surveys.index',
$survey->name
]
])

@section('content')
<form method="POST" action="{{ route('boilerplate.questions.store',$survey->id) }}" autocomplete="off" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-12 pb-3">
            <a href="{{ route("boilerplate.surveys.index") }}" class="btn btn-default" data-toggle="tooltip" title="@lang('boilerplate::surveys.returntolist')">
                <span class="far fa-arrow-alt-circle-left text-muted"></span>
            </a>
            <span class="btn-group float-right">
                <button type="submit" class="btn btn-primary">
                    @lang('boilerplate::surveys.save')
                </button>
            </span>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            @component('boilerplate::card', ['title' => 'boilerplate::surveys.add_question'])
            @if($errors->any())
            <div class="alert alert-danger">
                @php
                $displayedErrors = [];
                @endphp
                @foreach ($errors->all() as $error)
                @if (!in_array($error, $displayedErrors) && strpos($error, 'name') !== 0)
                <div>{{ $error }}</div>
                @php
                $displayedErrors[] = $error;
                @endphp
                @endif
                @endforeach
            </div>
            @endif
            @component('boilerplate::input', ['name' => 'name', 'label' => 'boilerplate::surveys.edit.name'])@endcomponent
            <p><button type="button" class="btn btn-info mt-3" id="add-option-btn">@lang('boilerplate::surveys.add_option')</button></p>
            <div class="tab-content">
                <div class="tab-pane fade show active" id="options" role="tabpanel" aria-labelledby="options-tab">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="options-table">
                            <thead>
                                <tr>
                                    <th>@lang('boilerplate::surveys.upload_files')</th>
                                    <th>@lang('boilerplate::surveys.correct_option')</th>
                                    <th>@lang('boilerplate::surveys.option_name')</th>
                                    <th>@lang('boilerplate::surveys.action')</th>
                                </tr>
                            </thead>
                            <tbody id="options-body">
                                <!-- First row -->
                                <tr class="option-row">
                                    <td>
                                        <label for="file_1">@lang('boilerplate::surveys.upload_file')</label>
                                        <input type="file" id="file_1" name="options[1][file]">
                                    </td>
                                    <td>
                                        <div class="form-check">
                                            <input class="form-check-input" type="hidden" value="off" name="options[1][correct]">
                                            <input class="form-check-input" type="checkbox" id="correct_1" name="options[1][correct]">
                                            <label class="form-check-label" for="correct_1">@lang('boilerplate::surveys.correct_option')</label>
                                        </div>
                                    </td>
                                    <td>
                                        <input type="text" id="option_name_1" name="options[1][option_name]" class="form-control">
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-danger delete-option">Delete</button>
                                    </td>
                                </tr>
                                <!-- Second row -->
                                <tr class="option-row">
                                    <td>
                                        <label for="file_2">@lang('boilerplate::surveys.upload_files')</label>
                                        <input type="file" id="file_2" name="options[2][file]">
                                    </td>
                                    <td>
                                        <div class="form-check">
                                            <input class="form-check-input" type="hidden" value="off" name="options[2][correct]">
                                            <input class="form-check-input" type="checkbox" id="correct_1" name="options[2][correct]">
                                            <label class="form-check-label" for="correct_2">@lang('boilerplate::surveys.correct_option')</label>
                                        </div>
                                    </td>
                                    <td>
                                        <input type="text" id="option_name_2" name="options[2][option_name]" class="form-control">
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-danger delete-option">Delete</button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            @endcomponent
        </div>
    </div>
</form>
@component('boilerplate::card', ['title' => 'boilerplate::surveys.list_question'])

@component('boilerplate::datatable', ['name' => 'questions']) @endcomponent

@endcomponent
<script>
    window.onload = function() {
        // Counter for unique IDs
        let optionCounter = 2;

        // Function to add a new option row to the table
        function addOptionRow() {
            optionCounter++;

            let optionRow = `<tr class="option-row">
        <td>
            <label for="file_${optionCounter}">@lang('boilerplate::surveys.upload_file')</label>
            <input type="file" id="file_${optionCounter}" name="options[${optionCounter}][file]">
        </td>
        <td>
            <div class="form-check">
                <input class="form-check-input" type="hidden" value="off" name="options[${optionCounter}][correct]">
                <input class="form-check-input" type="checkbox" id="correct_${optionCounter}" name="options[${optionCounter}][correct]">
                <label class="form-check-label" for="correct_${optionCounter}">@lang('boilerplate::surveys.correct_option')</label>
            </div>
        </td>
        <td>
            <input type="text" id="option_name_${optionCounter}" name="options[${optionCounter}][option_name]" class="form-control">
        </td>
        <td>
            <button type="button" class="btn btn-danger delete-option">Delete</button>
        </td>
        </tr>
        `;

            $('#options-body').append(optionRow);
        }

        // Add option button click event
        $('#add-option-btn').click(function() {
            addOptionRow();
        });

        // Delete option button click event (delegated to handle dynamically added delete buttons)
        $('#options-body').on('click', '.delete-option', function() {
            $(this).closest('.option-row').remove();
        });

        // Add event listener for checkbox change
        document.addEventListener('change', function(event) {
            const checkbox = event.target;
            if (checkbox.type === 'checkbox') {
                checkbox.previousElementSibling.value = checkbox.checked ? 'on' : 'off';
            }
        });

    };
</script>
@endsection

resources/views/surveys/list.blade.php
@extends('boilerplate::layout.index', [
'title' => __('boilerplate::surveys.title'),
'subtitle' => __('boilerplate::surveys.list.title'),
'breadcrumb' => [
__('boilerplate::surveys.list.title') => 'boilerplate.surveys.index'
]
])

@section('content')
<div class="row">
    <div class="col-12 mbl">
        <span class="float-right pb-3">
            <a id="addSurveyButton" class="btn btn-primary">
                @lang('boilerplate::surveys.create.title')
            </a>
        </span>
    </div>
</div>



@component('boilerplate::card')

@component('boilerplate::datatable', ['name' => 'surveys']) @endcomponent

@endcomponent

<div class="row">
    <form method="POST" action="{{ route('boilerplate.surveys.store') }}" autocomplete="off">
        @csrf
        <div class="modal fade" id="createSurveyModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">@lang('boilerplate::surveys.create.title')</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @component('boilerplate::input', ['name' => 'name', 'label' => 'boilerplate::surveys.create.name'])@endcomponent
                        @component('boilerplate::select2', ['name' => 'status', 'label' => 'boilerplate::surveys.status', 'minimum-results-for-search' => '-1'])
                        <option value="1" @if (old('status', 1)=='1' ) selected="selected" @endif>@lang('boilerplate::surveys.active')</option>
                        <option value="0" @if (old('status')=='0' ) selected="selected" @endif>@lang('boilerplate::surveys.inactive')</option>
                        @endcomponent
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">@lang('boilerplate::surveys.close')</button>
                        <button type="submit" class="btn btn-primary">@lang('boilerplate::surveys.save')</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <form id="editForm" action="" method="POST">
        <div class="modal fade" id="editSurveyModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">@lang('boilerplate::surveys.edit.title')</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @csrf
                        @method('PUT')
                        @component('boilerplate::input', ['name' => 'survey_name', 'label' => 'boilerplate::surveys.create.name', 'id' => 'surveyName' ])@endcomponent
                        @component('boilerplate::select2', ['name' => 'survey_status', 'label' => 'boilerplate::surveys.status', 'id' => 'status', 'minimum-results-for-search' => '-1'])
                        <option value="1">@lang('boilerplate::surveys.active')</option>
                        <option value="0">@lang('boilerplate::surveys.inactive')</option>
                        @endcomponent
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">@lang('boilerplate::surveys.close')</button>
                        <button type="submit" class="btn btn-primary">@lang('boilerplate::surveys.save')</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // show add survey modal
        document.getElementById('addSurveyButton').addEventListener('click', function() {
            $('#createSurveyModal').modal('show')
        });
        // error ADD survey modal
        var name = <?php echo json_encode($errors->has(['name'])) ?>;
        var status = <?php echo json_encode($errors->has(['status_select'])) ?>;
        if (name || status) {
            $('#createSurveyModal').modal('show');
        }

        // add data to the edit modal
        $(document).on('click', '.edit-button', function() {
            var surveyId = $(this).data('id');
            $.ajax({
                url: "{{ route('boilerplate.surveys.show', ['survey' => '__surveyId__']) }}".replace('__surveyId__', surveyId),
                method: 'GET',
                success: function(data) {
                    $('#surveyName').val(data.name);
                    $('#status').val(data.status).trigger('change');
                    $('#editForm').attr('action', "{{ route('boilerplate.surveys.update', ['survey' => '__surveyId__']) }}".replace('__surveyId__', surveyId));
                },
                error: function(error) {
                    console.log(error)
                }
            });
        });


    });
</script>
@endsection

@push('css')
<style>
    .img-circle {
        border: 1px solid #CCC
    }
</style>
@endpush